// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/23/2025, 11:44:56 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/magut/25_Journals/app/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/magut/25_Journals/app/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/magut/25_Journals/app/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/magut/25_Journals/app/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/magut/25_Journals/app/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/magut/25_Journals/app/frontend/composables/**/*.{js,ts,mjs}","C:/Users/magut/25_Journals/app/frontend/utils/**/*.{js,ts,mjs}","C:/Users/magut/25_Journals/app/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/magut/25_Journals/app/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/magut/25_Journals/app/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/magut/25_Journals/app/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;